doc: add usage example
libp2p/js-libp2p-webrtc-direct pull request #22
Opened 2018-09-09 10:27 UTC by backkem

Adds usage example to match libp2p/js-libp2p-tcp.

closes #21.

2018-09-09 10:46 UTC, backkem commented
I'm not sure what Jenkins is falling over. @vasco-santos maybe you can have a look?

2018-09-20 11:14 UTC, vasco-santos commented
Thanks for your PR @backkem 

I will restart Jenkins for you and review your PR

2018-09-20 11:21 UTC, vasco-santos requested changes
Thank you for the PR @backkem 

I requested just a small change and then I will be able to merge it.

2018-09-20 11:21 UTC, vasco-santos commented on README.md
> +const direct = new WebRTCDirect()
Can you change for this:

```js
const webRTCDirect = new WebRTCDirect()
```

I think direct is kind of an unclear name.

2018-09-26 13:50 UTC, vasco-santos commented
Hello @backkem 

Please rebase your PR with the new commits in master. After that, CI will hopefully be green again 🚀

2018-09-26 13:59 UTC, backkem commented
Re-based. Seems like the CI is completely gone now.

2018-09-26 14:17 UTC, vasco-santos approved these changes

2018-09-26 14:17 UTC, merged